package top.ppmblszdp.system.application.service.dept.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import top.ppmblszdp.common.exception.BusinessException;
import top.ppmblszdp.system.domain.model.dept.entity.Department;
import top.ppmblszdp.system.domain.model.dept.repository.DepartmentRepository;
import top.ppmblszdp.system.interfaces.web.dept.dto.DepartmentDTO;

@ExtendWith(MockitoExtension.class)
@DisplayName("部门应用服务测试")
public class DepartmentApplicationServiceImplTest {

  @Mock private DepartmentRepository departmentRepository;

  @InjectMocks private DepartmentApplicationServiceImpl departmentService;

  private Department department;
  private DepartmentDTO departmentDTO;

  @BeforeEach
  void setUp() {
    department = Department.create("HR Department", "HR01", null, 1);
    // Use reflection or a test-only setter to set ID since it's normally generated by JPA
    // For simplicity in this test, we can just assume the save returns an entity with ID
    departmentDTO =
        new DepartmentDTO(1L, null, "HR Department", "HR01", null, null, null, null, 1, 0);
  }

  @Test
  @DisplayName("创建部门")
  void createDepartment() {
    when(departmentRepository.save(any(Department.class))).thenReturn(department);

    DepartmentDTO result = departmentService.createDepartment(departmentDTO);

    assertEquals("HR Department", result.deptName());
    verify(departmentRepository, times(1)).save(any(Department.class));
  }

  @Test
  @DisplayName("根据 ID 获取部门")
  void getDepartmentById() {
    when(departmentRepository.findById(1L)).thenReturn(Optional.of(department));

    Optional<DepartmentDTO> result = departmentService.getDepartmentById(1L);

    assertTrue(result.isPresent());
    assertEquals("HR Department", result.get().deptName());
  }

  @Test
  @DisplayName("获取所有部门")
  void getAllDepartments() {
    when(departmentRepository.findAll()).thenReturn(Arrays.asList(department));

    List<DepartmentDTO> result = departmentService.getAllDepartments();

    assertEquals(1, result.size());
    assertEquals("HR Department", result.get(0).deptName());
  }

  @Test
  @DisplayName("更新部门")
  void updateDepartment() {
    when(departmentRepository.findById(1L)).thenReturn(Optional.of(department));
    when(departmentRepository.save(any(Department.class))).thenReturn(department);

    DepartmentDTO updatedDTO =
        new DepartmentDTO(1L, null, "Updated HR", "HR01", null, null, null, null, 1, 0);

    DepartmentDTO result = departmentService.updateDepartment(1L, updatedDTO);

    assertEquals("Updated HR", result.deptName());
    verify(departmentRepository, times(1)).save(any(Department.class));
  }

  @Test
  @DisplayName("更新部门-未找到")
  void updateDepartmentNotFound() {
    when(departmentRepository.findById(1L)).thenReturn(Optional.empty());

    assertThrows(
        BusinessException.class, () -> departmentService.updateDepartment(1L, departmentDTO));
  }

  @Test
  @DisplayName("删除部门")
  void deleteDepartment() {
    doNothing().when(departmentRepository).deleteById(1L);

    departmentService.deleteDepartment(1L);

    verify(departmentRepository, times(1)).deleteById(1L);
  }
}
