server:
  port: 9333

spring:
  profiles:
    active: dev # 默认激活开发环境
  threads:
    virtual:
      enabled: true
  application:
    name: ppmb-gateway
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
    gateway:
      server:
        webmvc:
          routes:
            - id: system-service-route
              uri: lb://ppmb-system
              predicates:
                - Path=/api/system/**
              filters:
                - StripPrefix=2
                - CircuitBreaker=systemCircuitBreaker,forward:/fallback
                - MyRateLimit
            - id: auth-service-route
              uri: lb://ppmb-auth
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
                - CircuitBreaker=authCircuitBreaker,forward:/fallback
                - MyRateLimit
            - id: user-service-route
              uri: lb://ppmb-system
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=2
                - CircuitBreaker=systemCircuitBreaker,forward:/fallback
                - MyRateLimit
            - id: ai-service-route
              uri: lb://ppmb-ai
              predicates:
                - Path=/api/ai/**
              filters:
                - StripPrefix=1
                - CircuitBreaker=systemCircuitBreaker,forward:/fallback
                - MyRateLimit
          cors:
            configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                  - "http://localhost:3001"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
 
ppmb:
  security:
    gateway-mode: true
    jwt:
      secret: "dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtcHVycG9zZXM=" # 32 bytes Base64

resilience4j:
  metrics:
    enabled: true
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 200
        minimumNumberOfCalls: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      authCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 1000
      systemCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 200
  ratelimiter:
    configs:
      default:
        limitForPeriod: 5000
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
    instances:
      authRateLimiter:
        baseConfig: default
      systemRateLimiter:
        baseConfig: default
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 200
        maxWaitDuration: 0s
    instances:
      authBulkhead:
        baseConfig: default
      systemBulkhead:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    urls:
      - name: ppmb-system
        url: /api/system/v3/api-docs
      - name: ppmb-auth
        url: /api/auth/v3/api-docs
