services:
  consul-server:
    image: consul:1.15.4 # 建议锁定版本号
    container_name: consul-server
    restart: always
    volumes:
      - ../ppmb-admin-docker-data/consul/data:/consul/data
      - ../ppmb-admin-docker-data/consul/config:/consul/config
    ports:
      - "8500:8500" # UI 界面和 HTTP API
      - "8600:8600/udp" # DNS 服务
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    networks:
      - ppmb-admin

  sonar-db:
    image: postgres:18
    container_name: sonar-db
    networks:
      - ppmb-admin
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - ../ppmb-admin-docker-data/sonar-db/data:/var/lib/postgresql

  ppmb-db:
    image: postgres:18
    container_name: ppmb-db
    networks:
      - ppmb-admin
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ppmb
    ports:
      - "5432:5432"
    volumes:
      - ../ppmb-admin-docker-data/ppmb-db/data:/var/lib/postgresql

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - ppmb-admin
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - sonar-db

  redis:
    image: redis:7-alpine
    container_name: ppmb-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../ppmb-admin-docker-data/redis/data:/data
    networks:
      - ppmb-admin

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: ppmb-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../ppmb-admin-docker-data/rabbitmq/data:/var/lib/rabbitmq
      - ../ppmb-admin-docker-data/rabbitmq/log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - ppmb-admin

networks:
  ppmb-admin:
    driver: bridge
