services:
  consul-server:
    image: consul:1.15.4 # 建议锁定版本号
    container_name: consul-server
    restart: always
    volumes:
      - ./.docker-volumes/consul/data:/consul/data
      - ./.docker-volumes/consul/config:/consul/config
    ports:
      - "8500:8500" # UI 界面和 HTTP API
      - "8600:8600/udp" # DNS 服务
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    networks:
      - ppmb-admin

networks:
  ppmb-admin:
    driver: bridge
