server:
  port: 8082

spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  application:
    name: ppmb-auth
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        ip-address: host.docker.internal
        health-check-path: /actuator/health
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
    openfeign:
      circuitbreaker:
        enabled: true
      micrometer:
        enabled: true

resilience4j:
  metrics:
    enabled: true
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 200
        minimumNumberOfCalls: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      remoteUserService:
        baseConfig: default
        slidingWindowSize: 1000
  ratelimiter:
    configs:
      default:
        limitForPeriod: 5000
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
    instances:
      remoteUserService:
        baseConfig: default
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 200
        maxWaitDuration: 0s
    instances:
      remoteUserService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces


  prometheus:
    metrics:
      export:
        enabled: true

ppmb:
  security:
    jwt:
      secret: "dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtcHVycG9zZXM="
