server:
  port: 8082

spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  application:
    name: ppmb-auth
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        ip-address: host.docker.internal
        health-check-path: /actuator/health
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
    openfeign:
      circuitbreaker:
        enabled: true
      micrometer:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      remoteUserService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
  ratelimiter:
    instances:
      remoteUserService:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces


  prometheus:
    metrics:
      export:
        enabled: true

ppmb:
  security:
    jwt:
      secret: "dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtcHVycG9zZXM="
