sonar.organization=pandaymx
sonar.projectKey=ppmb-admin-ui
sonar.branch.name=main
sonar.projectName=PPMB Admin UI
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/*.test.ts, dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
