server:
  port: 8081

ppmb:
  admin:
    init:
      password: "Ppmb@2026"


spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  application:
    name: ppmb-system
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ppmb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

resilience4j:
  metrics:
    enabled: true
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 200
        minimumNumberOfCalls: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
  ratelimiter:
    configs:
      default:
        limitForPeriod: 5000
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 200
        maxWaitDuration: 0s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
