/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    id("buildlogic.java-quality-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val libs = the<VersionCatalogsExtension>().named("libs")

dependencies {
    implementation(platform(libs.findLibrary("spring-boot-dependencies").get()))
    constraints {
        // Define dependency versions as constraints
        implementation(libs.findLibrary("commons-text").get())
    }
    implementation(libs.findLibrary("spring-boot-starter-log4j2").get())
    implementation(libs.findLibrary("disruptor").get())
}

configurations {
    all {
        exclude(group = "org.springframework.boot", module = "spring-boot-starter-logging")
    }
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("6.0.1")
            targets.all {
                testTask.configure {
                    finalizedBy(tasks.withType<JacocoReport>())
                }
            }
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("--enable-preview")
}

tasks.withType<Test>().configureEach {
    jvmArgs("--enable-preview")
}
