server:
  port: 8083

spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  application:
    name: ppmb-ai
  config:
    import: "optional:consul:"
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      aiService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      aiService:
        timeoutDuration: 60s
