name: Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

    - name: Set up JDK 25
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Build Docker image for ppmb-gateway
      run: docker build -t ppmb-gateway:latest ppmb-gateway
