name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ppmb-admin-ui/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'ppmb-admin-ui/**'

jobs:
  build-and-lint:
    name: Lint, Type Check and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ppmb-admin-ui

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: 1.1.7

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Linting
        run: bun run lint

      - name: Type Checking
        run: bun run tsc --noEmit

      - name: Production Build
        run: bun run build

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432 # v8.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          projectBaseDir: ppmb-admin-ui
